import { describe, expect, it } from "vitest";
import { normalizeStudioEventName, STUDIO_SSE_EVENTS } from "./use-sse";

describe("STUDIO_SSE_EVENTS", () => {
  it("covers the server lifecycle events that drive the UI", () => {
    expect(STUDIO_SSE_EVENTS).toEqual(expect.arrayContaining([
      "book:creating",
      "book:created",
      "book:deleted",
      "book:error",
      "write:start",
      "write:complete",
      "write:error",
      "draft:start",
      "draft:complete",
      "draft:error",
      "plan:start",
      "plan:success",
      "plan:fail",
      "compose:start",
      "compose:success",
      "compose:fail",
      "write-next:start",
      "write-next:success",
      "write-next:fail",
      "revise:start",
      "revise:progress",
      "revise:success",
      "revise:fail",
      "revise:unchanged",
      "rewrite:start",
      "rewrite:progress",
      "rewrite:success",
      "rewrite:fail",
      "rewrite:unchanged",
      "anti-detect:start",
      "anti-detect:progress",
      "anti-detect:success",
      "anti-detect:fail",
      "anti-detect:unchanged",
      "resync:start",
      "resync:progress",
      "resync:success",
      "resync:fail",
      "resync:unchanged",
      "resync:complete",
      "resync:error",
      "daemon:started",
      "daemon:stopped",
      "daemon:error",
      "audit:start",
      "audit:complete",
      "audit:error",
      "revise:complete",
      "revise:error",
      "rewrite:complete",
      "rewrite:error",
      "anti-detect:complete",
      "anti-detect:error",
      "agent:start",
      "agent:complete",
      "agent:error",
      "import:start",
      "import:complete",
      "import:error",
      "fanfic:start",
      "fanfic:complete",
      "fanfic:error",
      "fanfic:refresh:start",
      "fanfic:refresh:complete",
      "fanfic:refresh:error",
      "style:start",
      "style:complete",
      "style:error",
      "radar:start",
      "radar:complete",
      "radar:error",
      "log",
      "llm:progress",
      "ping",
    ]));
  });

  it("maps legacy lifecycle events to unified semantics", () => {
    expect(normalizeStudioEventName("revise:complete")).toBe("revise:success");
    expect(normalizeStudioEventName("revise:error")).toBe("revise:fail");
    expect(normalizeStudioEventName("rewrite:complete")).toBe("rewrite:success");
    expect(normalizeStudioEventName("rewrite:error")).toBe("rewrite:fail");
    expect(normalizeStudioEventName("resync:complete")).toBe("resync:success");
    expect(normalizeStudioEventName("resync:error")).toBe("resync:fail");
    expect(normalizeStudioEventName("anti-detect:error")).toBe("anti-detect:fail");
    expect(normalizeStudioEventName("rewrite:success")).toBe("rewrite:success");
  });
});
